### ISSUE TITLE
Butterknife 

### ISSUE THREAD

**Issue by denislearni** [geronimoagency/CoffeeScene-Android#1]
Hello, it looks like there is a problem using the library with butterknife.  Are you aware of this problem or it's just something that doesn't work only for me? 
Thanks

**Comment by denislearni** [comment]
Well, it definitely doesn't work with butterknife. pity

**Comment by RoRoche** [comment]
What about exposing a `View root(Object object)` method in the `SceneManager` class to get the root view group in which the scenes will be added (cf. `SceneManager.java`, line 243).
Or through the `ScenesMeta` associated to the `object` in the `sScenesMeta` map at line 266.

If doing so, the code using `SceneManager` and Butterkinfe could become:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SceneManager.create(this);
        ButterKnife.bind(this, SceneManager.root(this));
```

Or else, the `SceneManager.create` returns the root view itself. Giving us the ability to do the following call:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        View root = SceneManager.create(this);
        ButterKnife.bind(this, root);
```

**Comment by jeromec-geronimo** [comment]
Hello,

@RoRoche Thanks for your suggestion. `SceneManager.create` will returns the created view in the next version.

Otherwise, @denislearni you can use Butterknife with the SceneCreator like this:

```java
@Override
protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_event_details);
    SceneManager.create(
            SceneCreator.with(this)
                    .add(Scene.MAIN_CONTENT, R.id.activity_event_details_main_content)
                    .add(Scene.LOADER, R.id.activity_event_details_loader)
                    .add(Scene.PLACEHOLDER, R.id.activity_event_details_placeholder)
                    .main(Scene.LOADER)
    );
    ButterKnife.bind(this);
    ...
}
```

**Comment by jeromec-geronimo** [comment]
@denislearni can you copy past your code pls ?

butterknife works well on my side with:

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        SceneManager.create(this);
        ButterKnife.bind(this);
    }
```
