### ISSUE TITLE
Extension to add Conductor support

### ISSUE THREAD

**Issue by RoRoche** [geronimoagency/CoffeeScene-Android#3]
I'm a huge fan of the [bluelinelabs' Conductor library](https://github.com/bluelinelabs/Conductor) to build View-based Android applications.

Is it possible to add an extension (named `coffeescene-conductor` for example) to be able to call the `create` method with a Conductor's `Controller` object? It would be called as follows:

```java
@CoffeeScene({
        @Scene(scene = Scene.MAIN_CONTENT, layout = R.layout.sample_controller_main),
        @Scene(scene = Scene.LOADER, layout = R.layout.loader),
        @Scene(scene = Scene.PLACEHOLDER, layout = R.layout.placeholder)
})
public class HomeController extends Controller {

    @Override
    protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
        SceneManager.create(this);
        return SceneManager.root(this); // cf. https://github.com/geronimoagency/CoffeeScene-Android/issues/1#issuecomment-297329351
    }
}
```

**Comment by jeromec-geronimo** [comment]
Hi @RoRoche , this is now possible with the version 0.0.7
You can use:
```java
@Override
protected View onCreateView(@NonNull LayoutInflater inflater, @NonNull ViewGroup container) {
    return SceneManager.create(this, container.getContext());
}
```

(cf: https://github.com/geronimoagency/CoffeeScene-Android/commit/07d19cca6b0baa4f1a1b6683e957ba2740c5ea34)
